### PR TITLE
core: inherit diagnostic option in subtests

### LINKED ISSUE #984: [BUG] `--diag` option is not propagated to subtests
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the `CONTRIBUTING` guide on posting bugs, and `CODE_OF_CONDUCT`?

- [X] yes I read the things

### This issue exists in the latest tap version

- [X] I am using the latest tap

### Description

Hello! I encountered this while addressing #980 (trying to get the extension to correctly report test results w/ the corresponding code line)

### Expected

When using the `--diag` flag on the CLI, the `diag` field is present on all successful tests, including those in nested suites.

### Actual

The `diag` field is only present on all top-level tests, failing nested tests, **but not on passing nested tests**.

I guess the `diag` option does not get passed down to subtests properly?

### Reproduction

Run the following test:

```js
import t from "tap";

t.test("top-level OK", (t) => {
  t.equal("one", "one")
  t.end()
})

t.test("top-level KO", (t) => {
  t.equal("three", "four")
  t.end()
})

t.test("nesting A", (t) => {
  t.test("nested A OK", (t) => {
    t.equal("five", "five")
    t.end()
  })

  t.test("nested A KO", (t) => {
    t.equal("six", "seven")
    t.end()
  })

  t.end()
})
```

The following JSON is output with `npx tap myfile.test.js -R json --diag`. **I made a mistake while writing the original test file, the nested A tests are actually called top-level A,** use the fullname fields to find out what I'm talking about 🤦🏻 
<details>

<summary>This JSON is huge</summary>

```json
{
  "name": "TAP Tests",
  "level": 0,
  "plan": {
    "start": 1,
    "end": 1
  },
  "tests": 10,
  "failures": 2,
  "assertions": 4,
  "skipped": 0,
  "suites": [
    {
      "name": "hello.test.ts",
      "level": 1,
      "ok": false,
      "id": 1,
      "diag": {
        "stdio": "pipe",
        "cwd": "C:\\Users\\Matthieu\\vscode-node-tap\\example-workspace",
        "externalID": "hello.test.ts",
        "command": "C:\\Program Files\\nodejs\\node.exe",
        "args": [
          "--import=file:///C:/Users/Matthieu/vscode-node-tap/example-workspace/node_modules/.pnpm/@isaacs+ts-node-temp-fork-for-pr-2009@10.9.5_@types+node@20.10.4_typescript@5.2.2/node_modules/@isaacs/ts-node-temp-fork-for-pr-2009/import.mjs",
          "--import=file:///C:/Users/Matthieu/vscode-node-tap/example-workspace/node_modules/.pnpm/@tapjs+mock@1.2.15_@tapjs+core@1.4.6/node_modules/@tapjs/mock/dist/esm/import.mjs",
          "--enable-source-maps",
          "--import=file:///C:/Users/Matthieu/vscode-node-tap/example-workspace/node_modules/.pnpm/@tapjs+processinfo@3.1.6/node_modules/@tapjs/processinfo/dist/esm/import.mjs",
          "C:\\Users\\Matthieu\\vscode-node-tap\\example-workspace\\hello.test.ts"
        ],
        "exitCode": 1
      },
      "time": 1185.14,
      "fullname": "hello.test.ts",
      "closingTestPoint": true,
      "plan": {
        "start": 1,
        "end": 3
      },
      "tests": 9,
      "failures": 2,
      "assertions": 4,
      "skipped": 0,
      "suites": [
        {
          "name": "top-level OK",
          "level": 2,
          "ok": true,
          "id": 1,
          "diag": {
            "at": {
              "fileName": "hello.test.ts",
              "lineNumber": 3,
              "columnNumber": 3,
              "isToplevel": true
            },
            "source": "import t from \"tap\";\n\nt.test(\"top-level OK\", (t) => {\n--^\n  t.equal(\"one\", \"one\")\n  t.end()\n"
          },
          "time": 2.55,
          "fullname": "hello.test.ts > top-level OK",
          "closingTestPoint": true,
          "plan": {
            "start": 1,
            "end": 1
          },
          "tests": 1,
          "failures": 0,
          "assertions": 1,
          "skipped": 0,
          "cases": [
            {
              "ok": true,
              "name": "should be equal",
              "id": 1,
              "fullname": "hello.test.ts > top-level OK > should be equal"
            }
          ]
        },
        {
          "name": "top-level KO",
          "level": 2,
          "ok": false,
          "id": 2,
          "diag": {
            "at": {
              "fileName": "hello.test.ts",
              "lineNumber": 8,
              "columnNumber": 3,
              "isToplevel": true
            },
            "source": "})\n\nt.test(\"top-level KO\", (t) => {\n--^\n  t.equal(\"three\", \"four\")\n  t.end()\n"
          },
          "time": 5.162,
          "fullname": "hello.test.ts > top-level KO",
          "closingTestPoint": true,
          "plan": {
            "start": 1,
            "end": 1
          },
          "tests": 1,
          "failures": 1,
          "assertions": 1,
          "skipped": 0,
          "cases": [
            {
              "ok": false,
              "name": "should be equal",
              "id": 1,
              "diag": {
                "compare": "===",
                "at": {
                  "fileName": "hello.test.ts",
                  "lineNumber": 9,
                  "columnNumber": 5,
                  "typeName": "Test"
                },
                "stack": "Test.<anonymous> (hello.test.ts:9:5)\nhello.test.ts:8:3\n",
                "source": "\nt.test(\"top-level KO\", (t) => {\n  t.equal(\"three\", \"four\")\n----^\n  t.end()\n})\n",
                "diff": "--- expected\n+++ actual\n@@ -1,1 +1,1 @@\n-four\n+three\n"
              },
              "fullname": "hello.test.ts > top-level KO > should be equal"
            }
          ]
        },
        {
          "name": "nesting A",
          "level": 2,
          "ok": false,
          "id": 3,
          "diag": {
            "at": {
              "fileName": "hello.test.ts",
              "lineNumber": 13,
              "columnNumber": 3,
              "isToplevel": true
            },
            "source": "})\n\nt.test(\"nesting A\", (t) => {\n--^\n  t.test(\"top-level A OK\", (t) => {\n    t.equal(\"five\", \"five\")\n"
          },
          "time": 6.88,
          "fullname": "hello.test.ts > nesting A",
          "closingTestPoint": true,
          "plan": {
            "start": 1,
            "end": 2
          },
          "tests": 4,
          "failures": 1,
          "assertions": 2,
          "skipped": 0,
          "suites": [
            {
              "name": "top-level A OK",
              "level": 3,
              "ok": true,
              "id": 1,
              "time": 0.206,
              "fullname": "hello.test.ts > nesting A > top-level A OK",
              "closingTestPoint": true,
              "plan": {
                "start": 1,
                "end": 1
              },
              "tests": 1,
              "failures": 0,
              "assertions": 1,
              "skipped": 0,
              "cases": [
                {
                  "ok": true,
                  "name": "should be equal",
                  "id": 1,
                  "fullname": "hello.test.ts > nesting A > top-level A OK > should be equal"
                }
              ]
            },
            {
              "name": "top-level A KO",
              "level": 3,
              "ok": false,
              "id": 2,
              "diag": {
                "at": {
                  "fileName": "hello.test.ts",
                  "lineNumber": 19,
                  "columnNumber": 5,
                  "typeName": "Test"
                },
                "source": "  })\n\n  t.test(\"top-level A KO\", (t) => {\n----^\n    t.equal(\"six\", \"seven\")\n    t.end()\n"
              },
              "time": 3.541,
              "fullname": "hello.test.ts > nesting A > top-level A KO",
              "closingTestPoint": true,
              "plan": {
                "start": 1,
                "end": 1
              },
              "tests": 1,
              "failures": 1,
              "assertions": 1,
              "skipped": 0,
              "cases": [
                {
                  "ok": false,
                  "name": "should be equal",
                  "id": 1,
                  "diag": {
                    "compare": "===",
                    "at": {
                      "fileName": "hello.test.ts",
                      "lineNumber": 20,
                      "columnNumber": 7,
                      "typeName": "Test"
                    },
                    "stack": "Test.<anonymous> (hello.test.ts:20:7)\nTest.<anonymous> (hello.test.ts:19:5)\nhello.test.ts:13:3\n",
                    "source": "\n  t.test(\"top-level A KO\", (t) => {\n    t.equal(\"six\", \"seven\")\n------^\n    t.end()\n  })\n",
                    "diff": "--- expected\n+++ actual\n@@ -1,1 +1,1 @@\n-seven\n+six\n"
                  },
                  "fullname": "hello.test.ts > nesting A > top-level A KO > should be equal"
                }
              ]
            }
          ]
        }
      ]
    }
  ]
}
```

</details>

- ✅ The `top-level OK` test has a `diag` field
- ✅ The `top-level KO` test has a `diag` field
- ✅ The `nesting A` test has a `diag` field
- ❌ **The `nesting A > top-level A OK` test does not have a `diag` field**
- ✅ The  `nesting A > top-level A KO` test has a `diag` field

### Environment

I'll just put the `tap versions` here as I don't think the others are relevant

```
tap: 18.6.1
"@tapjs/config": 2.4.14
"@tapjs/core": 1.4.6
"@tapjs/run": 1.4.16
"@tapjs/stack": 1.2.7
"@tapjs/test": 1.3.17
tap-parser: 15.3.1
tap-yaml: 2.2.1
tcompare: 6.4.5
plugins:
  "@tapjs/after": 1.1.17
  "@tapjs/after-each": 1.1.17
  "@tapjs/asserts": 1.1.17
  "@tapjs/before": 1.1.17
  "@tapjs/before-each": 1.1.17
  "@tapjs/filter": 1.2.17
  "@tapjs/fixture": 1.2.17
  "@tapjs/intercept": 1.2.17
  "@tapjs/mock": 1.2.15
  "@tapjs/node-serialize": 1.2.6
  "@tapjs/snapshot": 1.2.17
  "@tapjs/spawn": 1.1.17
  "@tapjs/stdin": 1.1.17
  "@tapjs/typescript": 1.3.6
  "@tapjs/worker": 1.1.17
```

### PR DESCRIPTION
**Pull request by utybo**
Fixes #984

Can be tested in a simple local repo with pnpm (not sure if the `link:` works with npm):

**package.json**

```json
{
  "name": "testtap",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "tap": "link:/home/PATH/TO/TAPJS/src/tap"
  }
}
```

**hello.test.ts**

```ts
import t from "tap";

t.test("top-level OK", (t) => {
  t.equal("one", "one")
  t.end()
})

t.test("top-level KO", (t) => {
  t.equal("three", "four")
  t.end()
})

t.test("nesting A", (t) => {
  t.test("nested A OK", (t) => {
    t.equal("five", "five")
    t.end()
  })

  t.test("nested A KO", (t) => {
    t.equal("six", "seven")
    t.end()
  })

  t.end()
})
```

Then run,

```sh
pnpm exec tap hello.test.ts -R json --diag
```

And you'll see that nested A OK has diag data.

### CODE REVIEW

File: src/core/tap-snapshots/test/test-base.ts.test.cjs [hunk 1]
```diff
@@ -51,26 +51,6 @@ TAP version 14
...
-      test: child
-      source: |2
-            if (!subtest) throw new Error('did not get subtest')
-            await p
-            subtest.test('this should not work', async () => {})
-        ------------^
-          })
-          tb.end()
-      ...
-
```
Comment (utybo) [inline src/core/tap-snapshots/test/test-base.ts.test.cjs:73]: This (unrelated-to-my-changes) test was wrong from the beginning: since we're setting an explicit `diagnostics: false` in the parent test, we shouldn't be seeing diagnostics data here

Comment (isaacs) [reply src/core/tap-snapshots/test/test-base.ts.test.cjs:73]: Love it when the snapshots show that it wasn't actually working! It's like getting your repro for free :)
